"use strict";
const fs = require("node:fs");
const path = require("node:path");
const assert = require("node:assert/strict");
const { playwright, browserOptions } = require("./helpers.cjs");
const { fixtureServer } = require("./https-fixture.cjs");
const { managerFixture, managerChecks, target, st, manualUrl } = require("./manager-checks.cjs");
const root = path.resolve(__dirname, "..");
(async () => {
  const checks = []; const errors = []; const exchanges = [];
  const fixture = await fixtureServer((req, res, url) => {
    if (managerFixture(req, res, url, exchanges)) return;
    res.writeHead(200, { "content-type": "text/html;charset=utf-8" }); res.end("<!doctype html><html><body><h1>AdSkip 1.0 fixture</h1></body></html>");
  });
  const profile = fs.mkdtempSync(path.join(root, "work/extension-v1-profile-"));
  const extension = path.join(root, "extension");
  const launch = { headless: true, channel: "chromium", ...browserOptions(), viewport: { width: 1440, height: 900 }, args: ["--disable-extensions-except=" + extension, "--load-extension=" + extension, ...fixture.browserArgs] };
  let context;
  const report = { checkedAt: new Date().toISOString(), mode: "Unpacked MV3 extension, real options UI/messages/storage and HTTPS fixture server; browser-only host mapping; no Playwright network interception", outcome: "FAIL", checks, errors, exchanges };
  try {
    context = await playwright().chromium.launchPersistentContext(profile, launch); await context.grantPermissions(["clipboard-read", "clipboard-write"]);
    let worker = context.serviceWorkers()[0] || await context.waitForEvent("serviceworker"); const id = worker.url().split("/")[2];
    await worker.evaluate(() => chrome.storage.local.set({ autoOpen: false, adFilters: { "1short": false, ez4short: true, tech8s: false } }));
    const popup = await context.newPage(); popup.on("pageerror", (error) => errors.push(error.message));
    await popup.goto("chrome-extension://" + id + "/popup.html");
    const created = context.waitForEvent("page"); await popup.getByRole("button", { name: "Quản lý link", exact: true }).click();
    let manager = await created; await manager.waitForLoadState(); manager.on("pageerror", (error) => errors.push(error.message));
    assert.match(manager.url(), /options.html$/); checks.push("Popup opens native options page with the 1.0 manager");
    await managerChecks(manager, context, { name: "extension-v1", checks, exchanges });
    assert.deepEqual((await worker.evaluate(() => chrome.storage.local.get("adFilters"))).adFilters, { "1short": false, ez4short: true, tech8s: false });
    let ui = manager.locator("#adskip-manager"); await ui.getByRole("tab", { name: "Nhiều link", exact: true }).click();
    await ui.locator("#batch-input").fill(manualUrl); await ui.locator("#batch-start").click(); await ui.locator("#batch-message").filter({ hasText: "Đã xử lý xong danh sách." }).waitFor();
    await ui.locator("#batch-list .manual").getByRole("button", { name: "Tiếp tục", exact: true }).click();
    await ui.locator("#notice.error").filter({ hasText: "Mở bước" }).waitFor();
    const opened = context.waitForEvent("page"); await ui.getByRole("button", { name: "Mở bước", exact: true }).click(); const manual = await opened;
    await manual.locator("#adskip-widget").getByText("Cần thao tác trên trang", { exact: true }).waitFor({ timeout: 22000 });
    await manual.getByRole("button", { name: "Hoàn tất thao tác", exact: true }).click();
    const before = exchanges.filter((item) => item.path === "/v1-manual").length;
    await ui.getByRole("button", { name: "Tiếp tục", exact: true }).click();
    await ui.locator("#batch-list .resolved").waitFor(); assert.equal(exchanges.filter((item) => item.path === "/v1-manual").length, before);
    const state = (await worker.evaluate(() => chrome.storage.session.get("batch"))).batch;
    assert.equal(state.entries[0].url, target); assert.equal(state.entries[0].sourceUrl, manualUrl);
    checks.push("Batch manual continuation requires its explicitly opened tab, reads the fresh DOM after user action and makes no repeated GET");
    await manager.close();
    const reopened = context.waitForEvent("page"); await manual.locator("#adskip-widget").getByRole("button", { name: "Quản lý link", exact: true }).click();
    manager = await reopened; manager.on("pageerror", (error) => errors.push(error.message)); ui = manager.locator("#adskip-manager");
    await ui.locator("#batch-list .resolved").waitFor(); checks.push("Widget opens the manager again and session queue results survive closing its page");
    await worker.evaluate(() => chrome.storage.session.set({ batch: { phase: "running", revision: 100, message: "Reconstruction fixture", entries: [{ id: 1, phase: "resolved", sourceUrl: "https://gofile.io/d/completed", url: "https://gofile.io/d/completed", sourceLabel: "gofile.io/d/completed" }, { id: 2, phase: "resolving", sourceUrl: "https://ez4short.com/v1-final", sourceLabel: "ez4short.com/v1-final" }] } }));
    const cdp = await context.newCDPSession(manager); await cdp.send("ServiceWorker.enable"); await cdp.send("ServiceWorker.stopAllWorkers");
    await manager.reload(); await ui.locator("#batch-message").filter({ hasText: "Phiên xử lý bị ngắt" }).waitFor();
    assert.equal(await ui.locator("#batch-list .resolved").count(), 1); assert.equal(await ui.locator("#batch-list .stopped").count(), 1);
    await ui.locator("#batch-resume").click(); await ui.locator("#batch-message").filter({ hasText: "Đã xử lý xong danh sách." }).waitFor();
    assert.equal(await ui.locator("#batch-list .resolved").count(), 2);
    worker = context.serviceWorkers().find((item) => item.url().includes(id)) || await context.waitForEvent("serviceworker");
    checks.push("Actual service-worker stop/restart preserves completed rows, marks unfinished session rows interrupted and Resume completes them");
    const storedHistory = (await worker.evaluate(() => chrome.storage.local.get("history"))).history;
    assert.ok(storedHistory.length > 0); assert.ok(!JSON.stringify(storedHistory).includes("private-v1-key"));
    report.browser = context.browser().version(); await context.close(); context = await playwright().chromium.launchPersistentContext(profile, launch);
    worker = context.serviceWorkers()[0] || await context.waitForEvent("serviceworker");
    const stored = await worker.evaluate(() => chrome.storage.local.get(["history", "appSettings", "adFilters"]));
    assert.equal(stored.history.length, storedHistory.length); assert.equal(stored.appSettings.historyLimit, 25); assert.equal(stored.appSettings.batchDelayMs, 500);
    assert.deepEqual(stored.adFilters, { "1short": false, ez4short: true, tech8s: false });
    manager = await context.newPage(); await manager.goto("chrome-extension://" + id + "/options.html"); ui = manager.locator("#adskip-manager");
    await ui.getByRole("tab", { name: "Lịch sử", exact: true }).click(); await ui.locator("#history-list .row").first().waitFor();
    await ui.locator("#history-clear").click(); await ui.locator("#history-count").filter({ hasText: "0/0" }).waitFor();
    assert.equal((await worker.evaluate(() => chrome.storage.local.get("history"))).history.length, 0);
    checks.push("Browser restart preserves local history/settings/ad choices; Clear history removes persisted results");
    assert.deepEqual(errors, []); report.outcome = "PASS";
  } catch (error) {
    report.failure = error.message; if (context) for (const page of context.pages().filter((item) => item.url().includes("options.html"))) await page.screenshot({ path: path.join(root, "work/qa/extension-v1-failure.png") }).catch(() => {}); throw error;
  } finally { fs.writeFileSync(path.join(root, "work/extension-v1-result.json"), JSON.stringify(report, null, 2)); await context?.close(); await fixture.close(); }
  console.log(JSON.stringify(report, null, 2));
})().catch((error) => { console.error(error.stack); process.exitCode = 1; });
