"use strict";
const fs = require("node:fs");
const path = require("node:path");
const assert = require("node:assert/strict");
const root = path.resolve(__dirname, "..");
const target = "https://gofile.io/d/v1-fixture?sig=a%2Bb%3D&part=2#download";
const st = "https://ez4short.com/st?api=private-fixture&url=" + encodeURIComponent(target);
const fullPages = "https://1shortlink.com/api/v1/full-pages?api_key=private-v1-key&url=" + Buffer.from(target).toString("base64") + "&type=2";
const finalUrl = "https://ez4short.com/v1-final";
const manualUrl = "https://ez4short.com/v1-manual";
const expiredUrl = "https://ez4short.com/v1-expired";
function managerFixture(req, res, url, exchanges) {
  if (!url.pathname.startsWith("/v1-")) return false;
  exchanges.push({ host: url.hostname, path: url.pathname, run: url.searchParams.get("run"), method: req.method, at: Date.now() });
  const reply = (status, body) => { res.writeHead(status, { "content-type": "text/html;charset=utf-8" }); res.end(body); };
  const control = '<a id="get-link" class="get-link" href="' + target.replaceAll("&", "&amp;") + '">Get link</a>';
  if (url.pathname === "/v1-expired") reply(404, "Expired fixture");
  else if (url.pathname === "/v1-rate") reply(429, "Rate limited fixture");
  else if (url.pathname === "/v1-slow") setTimeout(() => reply(200, control), 2000);
  else if (url.pathname === "/v1-manual") reply(200, '<html><body><h1>Manual fixture</h1>' + control.replace('class="get-link"', 'class="get-link disabled"') + '<button id="verify">Hoàn tất thao tác</button><script>document.getElementById("verify").onclick=()=>document.getElementById("get-link").classList.remove("disabled");</script></body></html>');
  else reply(200, "<!doctype html><html><body>" + control + "</body></html>");
  return true;
}
async function waitQueue(ui, phrase) { await ui.locator("#batch-message").filter({ hasText: phrase }).waitFor({ timeout: 25000 }); }
async function managerChecks(page, context, options) {
  const { name, checks, exchanges } = options; const ui = page.locator("#adskip-manager");
  await ui.locator("#version").filter({ hasText: "1.0.0" }).waitFor();
  await ui.getByRole("tab", { name: "Cài đặt", exact: true }).click();
  await ui.locator("#setting-delay").selectOption("500"); await ui.locator("#setting-limit").selectOption("25");
  await ui.locator("#setting-auto-open").uncheck(); await ui.locator("#setting-history").check();
  await ui.getByRole("button", { name: "Lưu cài đặt", exact: true }).click();
  await ui.locator("#notice").filter({ hasText: "Đã lưu cài đặt." }).waitFor();
  checks.push(name + ": settings save delay/retention/history without changing ad preferences");
  await ui.getByRole("tab", { name: "Nhiều link", exact: true }).click();
  const countPages = context.pages().length;
  await ui.locator("#batch-input").fill([fullPages, st, finalUrl, manualUrl, expiredUrl, "invalid", fullPages].join("\n"));
  await ui.locator("#batch-start").click(); await waitQueue(ui, "Đã xử lý xong danh sách.");
  assert.equal(await ui.locator("#batch-list .row").count(), 6); assert.equal(await ui.locator("#batch-list .resolved").count(), 3);
  assert.equal(await ui.locator("#batch-list .manual").count(), 1); assert.equal(await ui.locator("#batch-list .error").count(), 2);
  assert.match(await ui.locator("#batch-progress").innerText(), /bỏ 1 link trùng/); assert.equal(context.pages().length, countPages);
  const sourceText = await ui.locator("#batch-list").innerText(); assert.ok(!sourceText.includes("private-v1-key")); assert.ok(!sourceText.includes(Buffer.from(target).toString("base64")));
  const batchCalls = exchanges.filter((entry) => ["/v1-final", "/v1-manual", "/v1-expired"].includes(entry.path));
  assert.equal(batchCalls.length, 3); assert.ok(batchCalls[1].at - batchCalls[0].at >= 450); assert.ok(batchCalls[2].at - batchCalls[1].at >= 450);
  checks.push(name + ": mixed batch deduplicates, keeps signed destinations, reports manual/expired/invalid rows, requests serially with 500ms delay and opens no tabs");
  await ui.locator("#batch-copy").click();
  assert.deepEqual((await page.evaluate(() => navigator.clipboard.readText())).split(/\r?\n/), [target, target, target]);
  checks.push(name + ": actual clipboard contains complete destination queries and fragments");
  const downloaded = page.waitForEvent("download"); await ui.locator("#batch-export").click(); const download = await downloaded;
  const exportPath = path.join(root, "work/qa/" + name + "-batch.json"); await download.saveAs(exportPath);
  const exportedText = fs.readFileSync(exportPath, "utf8"); const exported = JSON.parse(exportedText);
  assert.equal(exported.version, "1.0.0"); assert.equal(exported.results.length, 6); assert.equal(exported.results[0].url, target);
  assert.ok(!exportedText.includes("private-v1-key")); assert.ok(!exportedText.includes("sourceUrl")); assert.equal(exported.results[3].url, null);
  checks.push(name + ": downloaded JSON preserves full recognized targets and excludes source payloads/manual URLs");
  await ui.locator("#batch-input").fill(Array(51).fill(st).join("\n")); await ui.locator("#batch-start").click();
  await ui.locator("#notice.error").filter({ hasText: "50" }).waitFor(); assert.equal(await ui.locator("#batch-list .row").count(), 6);
  checks.push(name + ": 51-line input is rejected without replacing completed results");
  await ui.getByRole("tab", { name: "Lịch sử", exact: true }).click();
  await ui.locator("#history-list .row").first().waitFor();
  const initialHistory = await ui.locator("#history-list .row").count(); assert.ok(initialHistory >= 5);
  assert.ok(!await ui.locator("#history-list").innerText().then((text) => text.includes("private-v1-key")));
  await ui.locator("#history-phase").selectOption("manual"); assert.ok(await ui.locator("#history-list .manual").count() >= 1);
  assert.equal(await ui.locator("#history-list .row").count(), await ui.locator("#history-list .manual").count());
  await ui.locator("#history-phase").selectOption("resolved"); await ui.locator("#history-search").fill("gofile");
  assert.ok(await ui.locator("#history-list .row").count() >= 3);
  const opening = context.waitForEvent("page"); await ui.locator("#history-list .row").first().getByRole("button", { name: "Mở đích", exact: true }).click();
  const destination = await opening; await destination.waitForLoadState(); assert.equal(destination.url(), target); await destination.close();
  checks.push(name + ": explicit history Open creates a real destination tab with the complete URL");
  await ui.locator("#history-search").fill("no-such-destination"); assert.equal(await ui.locator("#history-list .row").count(), 0);
  await ui.locator("#history-search").fill(""); await ui.locator("#history-phase").selectOption("all");
  await ui.locator("#history-list .row").first().getByRole("button", { name: "Xóa", exact: true }).click();
  await ui.locator("#history-count").filter({ hasText: (initialHistory - 1) + "/" + (initialHistory - 1) }).waitFor();
  assert.equal(await ui.locator("#history-list .row").count(), initialHistory - 1);
  const historyDownload = page.waitForEvent("download"); await ui.locator("#history-export").click(); const historyFile = await historyDownload;
  const historyPath = path.join(root, "work/qa/" + name + "-history.json"); await historyFile.saveAs(historyPath);
  assert.equal(JSON.parse(fs.readFileSync(historyPath, "utf8")).results.length, initialHistory - 1);
  checks.push(name + ": history search/status filter, individual deletion and actual JSON download work");
  await ui.getByRole("tab", { name: "Cài đặt", exact: true }).click(); await ui.locator("#setting-history").uncheck();
  await ui.locator("#settings-save").click(); await ui.locator("#notice").filter({ hasText: "Đã lưu cài đặt." }).waitFor();
  await ui.getByRole("tab", { name: "Nhiều link", exact: true }).click();
  await ui.locator("#batch-input").fill("https://gofile.io/d/history-off"); await ui.locator("#batch-start").click(); await waitQueue(ui, "Đã xử lý xong danh sách.");
  await ui.getByRole("tab", { name: "Lịch sử", exact: true }).click(); assert.equal(await ui.locator("#history-list .row").count(), initialHistory - 1);
  await ui.getByRole("tab", { name: "Cài đặt", exact: true }).click(); await ui.locator("#setting-history").check(); await ui.locator("#settings-save").click();
  await ui.locator("#notice").filter({ hasText: "Đã lưu cài đặt." }).waitFor();
  checks.push(name + ": history off prevents new records while retaining existing history");
  await ui.getByRole("tab", { name: "Nhiều link", exact: true }).click();
  const run = name + "-stop";
  await ui.locator("#batch-input").fill("https://ez4short.com/v1-slow?run=" + run + "\nhttps://ez4short.com/v1-final?run=" + run);
  await ui.locator("#batch-start").click();
  for (let attempt = 0; attempt < 100 && !exchanges.some((item) => item.run === run); attempt++) await new Promise((resolve) => setTimeout(resolve, 30));
  assert.ok(exchanges.some((item) => item.run === run));
  await ui.locator("#batch-stop").click(); await waitQueue(ui, "Đã dừng hàng đợi.");
  await new Promise((resolve) => setTimeout(resolve, 2200));
  assert.equal(exchanges.filter((item) => item.run === run).length, 1); assert.equal(await ui.locator("#batch-list .stopped").count(), 2);
  await ui.locator("#batch-resume").click(); await waitQueue(ui, "Đã xử lý xong danh sách."); assert.equal(await ui.locator("#batch-list .resolved").count(), 2);
  checks.push(name + ": Stop aborts real in-flight transport, ignores late response and prevents next request; Resume completes remaining rows");
  await ui.locator("#batch-input").fill("https://ez4short.com/v1-rate?run=" + name + "\n" + st); await ui.locator("#batch-start").click();
  await waitQueue(ui, "tạm dừng"); assert.equal(await ui.locator("#batch-list .queued").count(), 1);
  await ui.locator("#batch-resume").click(); await waitQueue(ui, "Đã xử lý xong danh sách.");
  assert.equal(await ui.locator("#batch-list .error").count(), 1); assert.equal(await ui.locator("#batch-list .resolved").count(), 1);
  assert.equal(exchanges.filter((entry) => entry.path === "/v1-rate" && entry.run === name).length, 1);
  await ui.locator("#batch-list .resolved").getByRole("button", { name: "Tìm lại", exact: true }).click(); await waitQueue(ui, "Đã xử lý xong danh sách.");
  checks.push(name + ": HTTP 429 pauses pending rows; Resume does not retry the limited row; per-row retry preserves other results");
  await page.setViewportSize({ width: 1440, height: 900 }); await page.screenshot({ path: path.join(root, "work/qa/" + name + "-manager-desktop.png") });
  await page.setViewportSize({ width: 390, height: 844 }); await page.screenshot({ path: path.join(root, "work/qa/" + name + "-manager-mobile.png") });
  const bounds = await ui.boundingBox(); assert.ok(bounds.x >= 0 && bounds.x + bounds.width <= 390);
  assert.equal(await ui.evaluate((host) => host.shadowRoot.querySelector(".workspace").scrollWidth <= host.clientWidth), true);
  const batchTab = ui.getByRole("tab", { name: "Nhiều link", exact: true }); await batchTab.focus(); await page.keyboard.press("ArrowRight");
  assert.equal(await ui.getByRole("tab", { name: "Lịch sử", exact: true }).getAttribute("aria-selected"), "true");
  await page.keyboard.press("End"); assert.equal(await ui.getByRole("tab", { name: "Cài đặt", exact: true }).getAttribute("aria-selected"), "true");
  checks.push(name + ": manager fits 1440/390px viewports and supports keyboard tab navigation");
  await ui.getByRole("tab", { name: "Lịch sử", exact: true }).click();
  await page.screenshot({ path: path.join(root, "work/qa/" + name + "-manager-history.png"), fullPage: true });
  await ui.getByRole("tab", { name: "Cài đặt", exact: true }).click();
  await page.screenshot({ path: path.join(root, "work/qa/" + name + "-manager-settings.png"), fullPage: true });
  return { ui, initialHistory };
}
module.exports = { managerFixture, managerChecks, target, st, fullPages, finalUrl, manualUrl };
